-Must come up with a way to read the different lines.
-First line must always contain a number, which indicates the number of lines that will follow
	-How can I error check this to make sure that it does not have more or less than this #?
-Must count the number of words in each line (while ignoring the blank spaces).
-Must then output the number of words in each line in reverse order (report last line first).
-How will I use and implement dynamic allocation?